name: e2e_test
on:
  push:
    branches:
      - gh-action-e2e
  schedule:
    # Run every night.
    - cron:  '0 0 * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        supported_platforms: [aarch64]
        supported_os: [ubuntu, debian]
        rosdistro: [dashing, eloquent, melodic]
    steps:
    - name: Setup ROS2
      uses: ros-tooling/setup-ros2@0.0.11
      with:
        required-ros-distributions: ${{ matrix.rosdistro }}
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y qemu-user-static
    - name: Build packages
      uses: ros-tooling/action-ros2-ci@0.0.11
      with:
        package-name: cross_compile ros2run
    - name: Run e2e test
      run: |
        source ros2_ws/install/local_setup.bash && ros2_ws/src/cross_compile/test/run_e2e_test.sh -a ${{ matrix.supported_platforms }} -o ${{ matrix.supported_os }} -d ${{ matrix.rosdistro }}
